### ISSUE TITLE
Build fails: firebaseui.auth' has no exported member 'AuthResult

### ISSUE THREAD

**Issue by sgehrman** [RaphaelJenni/FirebaseUI-Angular#66]
$ npm run build-lib

Building Angular Package
Building entry point 'firebaseui-angular'
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc

BUILD ERROR
projects/firebaseui-angular-library/src/lib/firebaseui-angular-library.helper.ts(7,37): error TS2694: Namespace 'firebaseui.auth' has no exported member 'AuthResult'.
projects/firebaseui-angular-library/src/lib/firebaseui-angular-library.component.ts(137,70): error TS2694: Namespace 'firebaseui.auth' has no exported member 'AuthResult'.

Error: projects/firebaseui-angular-library/src/lib/firebaseui-angular-library.helper.ts(7,37): error TS2694: Namespace 'firebaseui.auth' has no exported member 'AuthResult'.
projects/firebaseui-angular-library/src/lib/firebaseui-angular-library.component.ts(137,70): error TS2694: Namespace 'firebaseui.auth' has no exported member 'AuthResult'.

    at Object.<anonymous> (/home/sgehrman/github/FirebaseUI-Angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at /home/sgehrman/github/FirebaseUI-Angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sgehrman/github/FirebaseUI-Angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/home/sgehrman/github/FirebaseUI-Angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/home/sgehrman/github/FirebaseUI-Angular/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at /home/sgehrman/github/FirebaseUI-Angular/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

projects/firebaseui-angular-library/src/lib/firebaseui-angular-library.helper.ts(7,37): error TS2694: Namespace 'firebaseui.auth' has no exported member 'AuthResult'.
projects/firebaseui-angular-library/src/lib/firebaseui-angular-library.component.ts(137,70): error TS2694: Namespace 'firebaseui.auth' has no exported member 'AuthResult'.

Error: projects/firebaseui-angular-library/src/lib/firebaseui-angular-library.helper.ts(7,37): error TS2694: Namespace 'firebaseui.auth' has no exported member 'AuthResult'.
projects/firebaseui-angular-library/src/lib/firebaseui-angular-library.component.ts(137,70): error TS2694: Namespace 'firebaseui.auth' has no exported member 'AuthResult'.

    at Object.<anonymous> (/home/sgehrman/github/FirebaseUI-Angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at /home/sgehrman/github/FirebaseUI-Angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sgehrman/github/FirebaseUI-Angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/home/sgehrman/github/FirebaseUI-Angular/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/home/sgehrman/github/FirebaseUI-Angular/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at /home/sgehrman/github/FirebaseUI-Angular/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

**Comment by sgehrman** [comment]
doesn't work with latest firebaseui
I had to hard code it to     "firebaseui": "3.0.0"

**Comment by RaphaelJenni** [comment]
Duplicates #65
